name: Generate ASCII

on: push

jobs:
  generate-ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: list repo files
        run: ls -ltra

      - name: Executing shell script
        run: ./ascii-script.sh
